### ISSUE TITLE
Member details do not indicate when member is static

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2-apidoc#10]
For example [Model::loadMultiple()](http://www.yiiframework.com/doc-2.0/yii-base-model.html#loadMultiple%28%29-detail) or [BaseYii::$app](http://www.yiiframework.com/doc-2.0/yii-baseyii.html#$app-detail).

The information that the method is static is important to the developer.

I like the way the PHP manual does it, with the `static` keyword in the signature, for example [DateTime::getLastErrors](http://php.net/manual/en/datetime.getlasterrors.php)

     public static array DateTime::getLastErrors ( void )

**Comment by samdark** [comment]
Good idea.

**Comment by cebe** [comment]
Fixed, thanks for reporting!
