### ISSUE TITLE
Exception is thrown in case target directory doesn't exist

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-apidoc#11]
```
Searching files to process... Exception 'yii\base\InvalidParamException' with message 'The dir argument must be a directory: /Users/samdark/src/yiiframework.com/data/yii-2.0/docs/guide'
```

Instead of throwing an exception it can create a directory.

**Comment by cebe** [comment]
how did you call it? it is supposed to create that dir already automatically. at least for me this works fine.

**Comment by samdark** [comment]
Confirmed that it's completely my issue. Sources weren't there yet.
