### ISSUE TITLE
The given file could not be interpreted as it contains errors: Errors parsing

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-apidoc#119]
### What steps will reproduce the problem?
$ vendor/bin/apidoc api ./api ~/apidocs
TargetDirectory already exists. Overwrite? (yes|no) [yes]:yes
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
14 files to update.
Processing files... 7% (1/14) ETA: n/a   **Error: The given file could not be interpreted as it contains errors: Errors parsing api/controllers/MeetingController.php**
### What's expected?
Generate the documentation

### What do you get instead?
$ vendor/bin/apidoc api ./api ~/apidocs
TargetDirectory already exists. Overwrite? (yes|no) [yes]:yes
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
14 files to update.
Processing files... 7% (1/14) ETA: n/a   Error: The given file could not be interpreted as it contains errors: Errors parsing api/controllers/MeetingController.php

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by dynasource** [comment]
can you post the contents of MeetingController.php?

**Comment by newscloud** [comment]
<?php

namespace api\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use api\models\UserToken;
use api\models\MeetingAPI;
use frontend\models\Meeting;
use frontend\models\MeetingPlace;
use frontend\models\MeetingTime;
use frontend\models\Participant;
use api\models\Service;

class MeetingController extends Controller
{
  /*const STATUS_PLANNING =0;
    const STATUS_SENT = 20;
    const STATUS_CONFIRMED = 40; // finalized
    const STATUS_COMPLETED = 50;
    const STATUS_EXPIRED = 55;
    const STATUS_CANCELED = 60;
    const STATUS_TRASH = 70;*/
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
      // your custom code here, if you want the code to run before action filters,
      // which are triggered on the [[EVENT_BEFORE_ACTION]] event, e.g. PageCache or AccessControl
      if (!parent::beforeAction($action)) {
          return false;
      }
      if (Service::verifyAccess(Yii::$app->getRequest()->getQueryParam('app_id'),Yii::$app->getRequest()->getQueryParam('app_secret'))) {
        return true;
      } else {
        echo 'your api keys are from the dark side';
        Yii::$app->end();
      }
    }

    public function actionList($app_id='', $app_secret='',$token='',$status=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return MeetingAPI::meetinglist($token,$status);
    }

    public function actionHistory($app_id='', $app_secret='',$token='',$meeting_id=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return MeetingAPI::history($token,$meeting_id);
    }

    public function actionMeetingplaces($app_id='', $app_secret='',$token='',$meeting_id=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      $meetingsObj = new \stdClass();
      // get user_id from $token
      $user_id =1;
      $places = MeetingPlace::find()
        ->where(['meeting_id'=>$meeting_id])
        ->orderBy(['created_at'=>SORT_DESC])
        ->all();
      $placesObj =[];
      foreach($places as $p) {
        $x = new \stdClass();
        $x->id = $p->id;
        $x->place_id = $p->place_id;
        $x->suggested_by = $p->suggested_by;
        $x->status = $p->status;
        $x->availability = $p->availability;
        $x->created_at = $p->created_at;
        $x->updated_at = $p->updated_at;
        $x->name = $p->place->name;
        $placesObj[]=$x;
      }
      return $placesObj;
    }

    public function actionMeetingtimes($app_id='', $app_secret='',$token='',$meeting_id=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      $meetingsObj = new \stdClass();
      // get user_id from $token
      $user_id =1;
      $times = Meetingtime::find()
        ->where(['meeting_id'=>$meeting_id])
        ->orderBy(['created_at'=>SORT_DESC])
        ->all();
      $timesObj =[];
      foreach($times as $t) {
        $timesObj[]=$t;
      }
      return $timesObj;
    }

    public function actionMeetingplacechoices($app_id='', $app_secret='',$token='',$meeting_place_id=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return MeetingAPI::meetingplacechoices($token,$meeting_place_id);
    }

    public function actionMeetingtimechoices($app_id='', $app_secret='',$token='',$meeting_time_id=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return MeetingAPI::meetingtimechoices($token,$meeting_time_id);
    }

    public function actionNotes($app_id='', $app_secret='',$token='',$meeting_id=0) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return MeetingAPI::notes($token,$meeting_id);
    }
}

**Comment by dynasource** [comment]
do you know which actionMethod is responsible for the error?

**Comment by rob006** [comment]
I can't reproduce it.

**Comment by dynasource** [comment]
@newscloud, can you debug MeetingController by removing parts and post the results of your research here?

**Comment by cebe** [comment]
can you please run the following command and paste the output: `php -l api/controllers/MeetingController.php`? Make sure to be in the correct directory which contains that path.

**Comment by newscloud** [comment]
First, thank you guys for your quick responses. I very much appreciate it. The Yii Team rocks!

I tried @cebe's request:
$ php -l api/controllers/MeetingController.php
No syntax errors detected in api/controllers/MeetingController.php

**Comment by newscloud** [comment]
Composer update and re-run seems to have fixed it. Sorry if I wasted your time. 

Do you think apidocs needs to check library versions?

**Comment by samdark** [comment]
It is checking library versions. Seems you were using older version of apidoc itself and newer version fixed the issue.
