### ISSUE TITLE
apidoc is publishing all of cebe/js-search

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2-apidoc#12]
![file tree](http://i.imgur.com/N79nvBS.png)

presumably only jssearch.js was desired.

i noticed when its PHP classes ended up in my project's documentation >8^O

**Comment by Faryshta** [comment]
same happens to me too. i solved it by adding `--exclude="docs,vendor"` to my command.

**Comment by cebe** [comment]
fixed, thanks for reporting!
