### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by blacksmoke26** [yiisoft/yii2-apidoc#120]
### What steps will reproduce the problem?
> composer require --prefer-dist yiisoft/yii2-apidoc
Using version ^2.0 for yiisoft/yii2-apidoc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-apidoc 2.0.1 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.2 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.3 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.4 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.5 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - Conclusion: don't install cebe/markdown-latex 1.0.0
    - Conclusion: remove cebe/markdown 1.1.1
    - Installation request for yiisoft/yii2-apidoc ^2.0 -> satisfiable by yiisoft/yii2-apidoc[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - Conclusion: don't install cebe/markdown 1.1.1
    - yiisoft/yii2-apidoc 2.0.0 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2].
    - Can only install one of: cebe/markdown[1.0.0, 1.1.1].
    - Can only install one of: cebe/markdown[1.0.1, 1.1.1].
    - Can only install one of: cebe/markdown[1.0.2, 1.1.1].
    - Installation request for cebe/markdown (locked at 1.1.1) -> satisfiable by cebe/markdown[1.1.1].

Installation failed, reverting ./composer.json to its original content.

### What's expected?

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| PHP version      | 7.0.13
| Operating system | Windows 8.1 x64

**Comment by cebe** [comment]
see https://github.com/yiisoft/yii2-apidoc/issues/72#issuecomment-226449236
