### ISSUE TITLE
resolve static return type

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2-apidoc#124]
and link to the correct class for it.

**Comment by arogachev** [comment]
@cebe Currently it's a bit unclear for me.  I know it's been a while, but could you provide more details / an example please?

**Comment by arogachev** [comment]
And is it still actual? @samdark

**Comment by samdark** [comment]
```php
class BaseHtml
{
    public static doit(): static
    {
    }
}

class Html extends BaseHtml
{
}
```

Generated docs for `Html::doit()` should return `Html`.

**Comment by arogachev** [comment]
Current implementation is based on parsing PHPDoc blocks. I'll move handling type hints to a separate issue later.

But parsing of this:

```php
* @return static
```

can be implemented though.

**Comment by arogachev** [comment]
I implemented basic resolving but found the blocker in current design. The catch is that links to details of inherited methods lead to the place it was originally declared (current class doesn't have details for such methods). For example: `ActiveRecord` (https://www.yiiframework.com/doc/api/2.0/yii-db-activerecord.) class page, check link for `instance()`. It's https://www.yiiframework.com/doc/api/2.0/yii-base-staticinstancetrait#instance()-detail.

So replacing `static` without context doesn't make sense there. Replacing `static` only with current class is not much useful too. What we should do? Include inherited methods' details at the current class page? Or maybe it's now worth it? In Yii 2 `@return static` is rarely seen.

**Comment by arogachev** [comment]
Another edge case is traits with resolved conflicts for used methods or some kind of dynamic class calculation. But I guess it's rare, especially in conjunction with `static` and can be ignored for now.

**Comment by arogachev** [comment]
> Include inherited methods' details at the current class page?

After discussion we decided to choose this variant.
