### ISSUE TITLE
Q: What's the best way to use apidocs if arguments are sent by headers?

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-apidoc#125]
### What steps will reproduce the problem?
How do I generate documentation for this function? 

public function actionHeadertest($sig='') {
      $headers = Yii::$app->request->headers;
      $email= $headers->get('email');
      $firstname= $headers->get('firstname');
      $lastname= $headers->get('lastname');
      $oauth_token= $headers->get('oauth_token');
      $source = $headers->get('source');

What' the best way to solve this for myself?

I've considered create a mirror function with URL arguments just for the documentation, but that's unused.

**Comment by cebe** [comment]
The API usually documented with this library is the API of PHP classes, their properties and methods. This is not about documenting the API provided by your application in form of URLs. There are other documentation tools for that like http://swagger.io/ or https://apiblueprint.org/.

**Comment by newscloud** [comment]
Thanks for the suggestions. 
Okay, thanks ... one thing I though of after I posted was to put unused query arguments in such as 
public function actionHeadertest($sig='',$email='',$firstname='',$lastname='',$oauth_token='',$source='')

**Comment by cebe** [comment]
> one thing I though of after I posted was to put unused query arguments in such as
> public function actionHeadertest($sig='',$email='',$firstname='',$lastname='',$oauth_token='',$source='')

you can do that.
