### ISSUE TITLE
There's a minor error in the documentation

### ISSUE THREAD

**Issue by densityx** [yiisoft/yii2-apidoc#129]
### What steps will reproduce the problem?
No particular steps but then this is the link to the docs: http://www.yiiframework.com/doc-2.0/yii-web-application.html

### What's expected?
In the **Public Methods** section, the `__set(), __get() and etc` are supposed to be **Defined by** `yii\base\Component` instead of `yii\base\Object`

### What do you get instead?
`yii\base\Object` instead of `yii\base\Component`

**Comment by arogachev** [comment]
It's rendered as expected now. https://www.yiiframework.com/doc/api/2.0/yii-web-application
