### ISSUE TITLE
Virtual properties generation problem

### ISSUE THREAD

**Issue by piaoyii** [yiisoft/yii2-apidoc#132]
Hi!
I want to generate ducomention for my virtual properties，I have seen the [core-code-style.md](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md),  
it says:
`All virtual properties in classes that extend from yii\base\Object are documented with an @property tag in the class doc block. These annotations are automatically generated from the @return or @param tag in the corresponding getter or setter by running ./build php-doc in the build directory. You may add an @property tag to the getter or setter to explicitly give a documentation message for the property introduced by these methods when description differs from what is stated in @return.`
These words are too hard for me to understand although I read the `phpdoc`. 
so is not works!
The following code is mine:  
```
<?php
/**
 * @link a link
 * @copyright a Copyright (c) 
 * @license a license
 */

namespace app\models;

use yii\base\Component;

/**
 * @property int $test test1
 * @author piaoyii <sky@piaoyii.com>
 */
class Test extends Component
{
	/**
	 * @var int $test test2
	 */
	private $_test;

	/**
	 * test3
	 *
	 * test4
	 *
	 * @return int test5
	 */
	public function getTest()
	{
		$this->_test = 1213;
		return $this->_test;
	}
}
```
There is no 'public read-only property' in the generated 'api documention'!
But at last, I find if my mentioned 'Test.php' under the same directory with `yii\base\Object`.
It works!
I am not good at English,I don't know if you can understand me.But I said and need help!

**Comment by cebe** [comment]
Quite sure this should work. reopening as a bug to check it.

**Comment by kryvel** [comment]
Hi, any update on this ?
