### ISSUE TITLE
PhpParser Error with PHP 7 Anonymous Class

### ISSUE THREAD

**Issue by markch123** [yiisoft/yii2-apidoc#133]
### What steps will reproduce the problem?
This breaks yii2-apidoc (well PhpParser breaks).

            return json_encode(new class($applications, $name)
            {
                public $applications = "";
                public $fileToken = "";
                public $code = 200;

                public function __construct(array $applications, string $key)
                {
                    $this->applications = $applications;
                    $this->fileToken = $key;
                }
            });

### What's expected?

Cool looking documentation.

### What do you get instead?

Error:  Object of class PhpParser\Node\Stmt\Class_ could not be converted to string

### Additional info
Looks like we need to upgrade to PhpParser 2 so we can document anything with php7 anonymous classes.  It's not a huge hassle to bypass the issue as can easily break the class out (pre php7), but would be nice for the future.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 7.0
| Operating system | Ubuntu

**Comment by cebe** [comment]
Are you using the 2.1 version of apidoc or 2.0.x? 2.1 should have upgrade PHPParser already.

**Comment by markch123** [comment]
Yep but I think we should be using PHPParser v 2 (or maybe even 3). According to https://github.com/nikic/PHP-Parser, version  2 supports 7.0 while 3 supports 7.1.
I believe we are using v1.4.1.

**Comment by cebe** [comment]
OH, now I see what you mean. I have upgrade from 0.9 to 1.x, did not know that there was already a 3.x version out. Will check it, thanks for reporting!
