### ISSUE TITLE
Using 'minted' instead of 'listing' in LaTeX/PDF output

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2-apidoc#134]
Is there an easy way to use [minted](https://www.ctan.org/pkg/minted) package instead of `listing` when using the PDF output? IMHO, it brings a much better syntax highlighting.

**Comment by cebe** [comment]
I was looking for something that improves the code highlighting. minted looks promising. Thanks for the suggestion!

**Comment by ricpelo** [comment]
A pleasure! :)
