### ISSUE TITLE
Add support for `@method` tags

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2-apidoc#136]
https://github.com/yiisoft/yii2-gii/pull/90

**Comment by Thoulah** [comment]
Tagging along. Now I don't need to create new issue :+1: 
https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.method.pkg.html

**Comment by arogachev** [comment]
The support was already added in #192, I'll try to retest it.

**Comment by arogachev** [comment]
I'll describe new problems in new issues. The current issue seems to be a duplicate and already solved.
