### ISSUE TITLE
Add small blurb on significance of README.md

### ISSUE THREAD

**Issue by markch123** [yiisoft/yii2-apidoc#139]
Hi, 

It would be great to have a small blurb on the importance of  README.md and how this is used to create an index. Something like.....

"By default the "guide" renderer/template will create a bootstrap row split into two columns (md2 and md10). The guide renderer will generate an index for the first column based on the existence of an README.md. Please check "here" for an example README.md. If a README.md is not included this column is left blank. "

ta
mark

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by arogachev** [comment]
Mentioning layout details is unnecessary I think. The rest of the info was added to a separate note, thanks.
