### ISSUE TITLE
vendor/bin/apidoc api /path..../models ./output

### ISSUE THREAD

**Issue by wmfunk** [yiisoft/yii2-apidoc#14]
vendor/bin/apidoc api /path..../models ./output

Searching files to process... done.
Loading apidoc data from cache... done.
Checking for updated files... done.
0 files to update.
Processing files... done.
Updating cross references and backlinks... done.
Rendering files: 0% (0/36) ETA: n/a   Error: array_unshift() expects parameter 1 to be array, object given

any ideas?

**Comment by cebe** [comment]
can you set YII_DEBUG to true here: https://github.com/yiisoft/yii2-apidoc/blob/master/apidoc#L11 and give me the full error stack trace?

**Comment by wmfunk** [comment]
Thank You for Your answer but after the latest updating the problem was solved
