### ISSUE TITLE
"Invalid argument supplied for foreach()" errors for a particular class/interface hierarchy when running api doc generator

### ISSUE THREAD

**Issue by angrybrad** [yiisoft/yii2-apidoc#141]
### What steps will reproduce the problem?

Given a class/interface hierarchy like this:

My class:
`class ElementQuery extends Query implements ElementQueryInterface`

My interface:
`interface ElementQueryInterface extends \yii\db\QueryInterface, \ArrayAccess, \Arrayable, \Countable, \IteratorAggregate`

My class:
`class Query extends \yii\db\Query`

Yii 2 class:
`class Query extends Component implements QueryInterface`

Running the api doc generator produces several `Invalid argument supplied for foreach()` errors because there are several places where the code is assuming an interface would have properties or a parent class, for example.

### What's expected?

No error.

### What do you get instead?

An error.

### Additional info

Pull request incoming with some guard checks.

**Comment by arogachev** [comment]
https://github.com/yiisoft/yii2-apidoc/pull/142#issuecomment-527619298 So the issue should be closed as well. Feel free to reopen it if you find a way to reproduce the bug.
