### ISSUE TITLE
@inheritdoc tag doesn't work for third party projects

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2-apidoc#15]
https://github.com/Chofoteddy/yii2-bootstrap-wizard/blob/master/WizardAsset.php this class with the command

`./vendor/bin/apidoc api . docs/json --exclude="docs,vendor"`

return this https://github.com/Chofoteddy/yii2-bootstrap-wizard/blob/master/docs/classes/chofoteddy-wizard-wizardasset.html html which doesn't contain any information about the properties documented with @inheritdoc tag.

**Comment by cebe** [comment]
are you including the yii framework classes when creating the docs? the interiting of docs only works if the partent class is included.

**Comment by Faryshta** [comment]
how can i include it? the docs for the apidoc are unexistant

**Comment by cebe** [comment]
the first argument can take multiple directories separated by `,`.

```
./vendor/bin/apidoc api path/to/yii/framework/,. docs/json --exclude="docs,vendor"
```

**Comment by samdark** [comment]
Should be documented, I guess...
