### ISSUE TITLE
Constants are missing 

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2-apidoc#150]
It seems that some constants are missing when generating the api doc (as json):

For testing purposes i use the following folder to generate the json from

https://github.com/luyadev/luya/tree/master/modules/admin/src/base

The command to generate

```sh
./vendor/bin/apidoc api vendor/luyadev/luya/modules/admin/src/base/ runtime/foobar --template=json
```

below the json output for a given class:

### Property.php

https://github.com/luyadev/luya/blob/1182fbf1e83c34b2a9c81da57e2ae97d7d7e3f28/modules/admin/src/base/Property.php

```json
"luya\\admin\\base\\Property": {
        "parentClass": "yii\\base\\Component",
        "isAbstract": true,
        "isFinal": false,
        "interfaces": [
            "luya\\admin\\base\\TypesInterface"
        ],
        "traits": [],
        "subclasses": [
            "luya\\admin\\base\\CheckboxArrayProperty",
            "luya\\admin\\base\\CheckboxProperty",
            "luya\\admin\\base\\ImageProperty"
        ],
        "events": [],
        "constants": {
            "EVENT_BEFORE_RENDER": {
                "definedBy": "luya\\admin\\base\\Property",
                "value": "'EVENT_BEFORE_RENDER'",
                "phpDocContext": {},
                "name": "EVENT_BEFORE_RENDER",
                "sourceFile": null,
                "startLine": 22,
                "endLine": 22,
                "shortDescription": "",
                "description": "",
                "since": null,
                "deprecatedSince": null,
                "deprecatedReason": null,
                "tags": [
                    {}
                ]
            }
        },
```

Renders constants as expected.

### TypesInterface.php
https://github.com/luyadev/luya/blob/1182fbf1e83c34b2a9c81da57e2ae97d7d7e3f28/modules/admin/src/base/TypesInterface.php

```php
    "luya\\admin\\base\\TypesInterface": {
        "parentInterfaces": [],
        "implementedBy": [
            "luya\\admin\\base\\CheckboxArrayProperty",
            "luya\\admin\\base\\CheckboxProperty",
            "luya\\admin\\base\\Property",
            "luya\\admin\\base\\ImageProperty"
        ],
        "authors": {
            "Basil Suter": "basil@nadar.io"
        },
        "methods": [],
        "properties": null,
        "namespace": "luya\\admin\\base",
        "phpDocContext": {},
        "name": "luya\\admin\\base\\TypesInterface",
        "sourceFile": "vendor\/luyadev\/luya\/modules\/admin\/src\/base\/TypesInterface.php",
        "startLine": 10,
        "endLine": 150,
        "shortDescription": "TypesInterface represents all possible types for properties or blocks.",
        "description": "",
        "since": null,
        "deprecatedSince": null,
        "deprecatedReason": null,
        "tags": []
    },

```

Now types interfaces contains only constants, but the api renderer nothing, not even an empty array as its usual when no constants are defined `"constants": [],`

Sorry for the large issue text :-)

> Maybe because its an interface.

**Comment by cebe** [comment]
> Maybe because its an interface.

probably. we have no interface that defines any constants in Yii, so we did not notice this bug.

**Comment by nadar** [comment]
@cebe if you give me a few hints (line, class) where the constants are collected, or on which part you collect those informations, i am going to make a PR (if i find the bug then :-)).

**Comment by cebe** [comment]
@nadar check the TypeDoc class and subclasses ClassDoc and InterfaceDoc, ClassDoc collects constancts in __construct(), InterfaceDoc does not. As traits can not have constants, we can not move it to TypeDoc but have to add it to InterfaceDoc too. 

This is the collection phase, the templates may need to be adjusted to retrieve the info afterwards. e.g. here: https://github.com/yiisoft/yii2-apidoc/blob/66ee5788b5b6ff0c9f396e09011ba5f449cbc772/templates/html/views/type.php#L41
