### ISSUE TITLE
Not process classes with visibility of class constants

### ISSUE THREAD

**Issue by brussens** [yiisoft/yii2-apidoc#155]
### Additional info
The generator skips classes with visibility for constants. For example generation for this class will not be done.
```php
class User
{
    public const STATUS_CONST = 1;
}
```

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13.1
| PHP version      | 7.1.8
| Operating system | WIN10X64

**Comment by cebe** [comment]
https://wiki.php.net/rfc/class_const_visibility
