### ISSUE TITLE
External reference is not available anymore

### ISSUE THREAD

**Issue by Eseperio** [yiisoft/yii2-apidoc#158]
In [Prepare application for scaling](http://www.yiiframework.com/doc-2.0/guide-tutorial-performance-tuning.html#prepare-application-for-scaling) there is a link to an external resource that is not available. It points to http://thehighload.com/ , but this site is currently closed.

**Comment by cebe** [comment]
Thanks for reporting, any idea why it is gone or who is the author? Content is still available through archive.org https://web.archive.org/web/20170311200133/http://thehighload.com/

**Comment by Eseperio** [comment]
No, IDK, just found that link was dead

**Comment by samdark** [comment]
golotyuk@gmail.com is the author. Website is available in Russian: https://ruhighload.com/

**Comment by samdark** [comment]
Not sure why English version was closed.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/f72f7c7406798423228b379c72a4bf9104d937ee
