### ISSUE TITLE
Relative link from extension readme to extension docs isn't rendered correctly

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-apidoc#159]
### What steps will reproduce the problem?

http://www.yiiframework.com/doc-2.0/ext-bootstrap-index.html

### What's expected?

"Documentation is at docs/guide/README.md" links to readme.

### What do you get instead?

http://www.yiiframework.com/doc-2.0/docs/guide/README.md

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | any
| PHP version      | any
| Operating system | any

**Comment by cebe** [comment]
related to https://github.com/yiisoft-contrib/yiiframework.com/issues/19
