### ISSUE TITLE
FR: Allow Markdown formatting in custom cross link labels

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2-apidoc#161]
We often use custom cross link labels to describe the actual code that should be used to reference a method/property. For example:

> <img width="597" alt="screen shot 2018-01-19 at 8 16 14 pm" src="https://user-images.githubusercontent.com/47792/35179779-aa12f0c0-fd55-11e7-92e9-6d7baebd8e00.png">

When doing so, we want the reference label to be wrapped in a `<code>` tag. However the only way to do that is to actually type out the `<code>` tag in the custom label text, like so:

```
[[ApplicationTrait::getEntries()|<code>Craft::$app->entries</code>]]
```

It would be nice if we could swap the `<code>` and `</code>` tags with backticks (`):

```
[[ApplicationTrait::getEntries()|`Craft::$app->entries`]]
```

However custom cross link labels are currently not parsed as Markdown, so the backtics get included in the generated output verbatim:

```html
<a href="craft-base-applicationtrait.html#getEntries()-detail">`Craft::$app->entries`</a>
```

**Comment by samdark** [comment]
How about `\`[[ApplicationTrait::getEntries()|<code>Craft::$app->entries</code>]]\``?

**Comment by brandonkelly** [comment]
(Assuming you meant to remove the `<code>` and `</code>` tags…)

I tried that; it ends up as

```html
<code>[[ApplicationTrait::getEntries()|Craft::$app->entries]]</code>
```

**Comment by samdark** [comment]
OK.
