### ISSUE TITLE
PHP-Files/Classes are missing 

### ISSUE THREAD

**Issue by WeeSee** [yiisoft/yii2-apidoc#162]
### What steps will reproduce the problem?
When building the docs using   `../basic/vendor/bin/apidoc api . ./docs  --exclude="docs" --page-title="WeeSee/PdfLabel"` the docs generated look perfect but there is only one PHP file (`TCPDFLabel.php`) included in the docs.

The directory:
```
-rw-rw-r-- 1 weesee weesee  7864 Jan 21 20:26 PdfLabel.php
-rw-rw-r-- 1 weesee weesee 1355 Jan 21 20:00 README.md
-rw-rw-r-- 1 weesee weesee 1108 Jan 21 20:41 TCPDFLabel.php
-rw-rw-r-- 1 weesee weesee  189 Jan 21 20:32 tools.md
```

### What's expected?
I expect both PHP files (one class per file) in the docs.

### What do you get instead?
I do ony get one PHP file (TCPDFLabel.php)

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         |  "~2.0.13"
| Yii APIDoc version | "~2.1.0"
| PHP version        |  7.0.22
| Operating system   | Ubuntu 16.04.3 LTS

**Comment by samdark** [comment]
https://github.com/WeeSee/yii2-pdflabel ?

**Comment by WeeSee** [comment]
yes

**Comment by WeeSee** [comment]
Here is some additional info: This is the command line view when executing apidoc:

```
TargetDirectory already exists. Overwrite? (yes|no) [yes]:
Searching files to process... done.
Loading apidoc data from cache... done.
Checking for updated files... done.
0 files to update.
Processing files... done.
Updating cross references and backlinks... done.
Rendering files: done.
generating extension index files...done.
generating search index...done.
```

**Comment by cebe** [comment]
looks like phpdocumentors `FileReflector` does not find any class in the file. could be related to #146

**Comment by Thoulah** [comment]
Missing about half of my files. Any known workarounds?
