### ISSUE TITLE
PHP 7.2 Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2-apidoc#165]
### What steps will reproduce the problem?
run ./vendor/bin/apidoc api . --exclude="vendor"
### What's expected?
Generate APIDoc 
### What do you get instead?
PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name in /home/nestor/public_html/openbiblio2/vendor/yiisoft/yii2-apidoc/models/BaseDoc.php on line 12

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.15.1
| Yii APIDoc version | latest
| PHP version        | 7.2.4
| Operating system   | openSUSE Tumbleweed
```
PHP 7.2 Cannot use yii\base\Object as Object because 'Object' is a special class name in vendor/yiisoft/yii2-apidoc/models/BaseDoc.php on line 12
```
Changing in this line **Object** to **BaseObject** and in the class extension doing the same, this error is solved only for this file but is replicated in `models/ParamDoc.php` on line 11 and so on in each class that extends **Object**

**Comment by PommeVerte** [comment]
Experiencing this as well.

**Comment by samdark** [comment]
@cebe is it release time?
