### ISSUE TITLE
Bug with BaseObject in apidoc

### ISSUE THREAD

**Issue by pvsaintpe** [yiisoft/yii2-apidoc#169]
Please create new tag (or release from master:branch), ex.: 2.1.1 (with commit where Object renamed to BaseObject).
composer update with * (branch master) not working, only with tags.

Searching files to process... done.
Loading apidoc data from cache... PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name in /vagrant/platproc/vendor/yiisoft/yii2-apidoc/models/BaseDoc.php on line 12
PHP Stack trace:
PHP   1. {main}() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/apidoc:0
PHP   2. yii\console\Application->run() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/apidoc:53
PHP   3. yii\console\Application->handleRequest() /vagrant/platproc/vendor/yiisoft/yii2/base/Application.php:386
PHP   4. yii\console\Application->runAction() /vagrant/platproc/vendor/yiisoft/yii2/console/Application.php:147
PHP   5. yii\console\Application->runAction() /vagrant/platproc/vendor/yiisoft/yii2/console/Application.php:180
PHP   6. yii\apidoc\commands\ApiController->runAction() /vagrant/platproc/vendor/yiisoft/yii2/base/Module.php:528
PHP   7. yii\apidoc\commands\ApiController->runAction() /vagrant/platproc/vendor/yiisoft/yii2/console/Controller.php:148
PHP   8. yii\base\InlineAction->runWithParams() /vagrant/platproc/vendor/yiisoft/yii2/base/Controller.php:157
PHP   9. call_user_func_array:{/vagrant/platproc/vendor/yiisoft/yii2/base/InlineAction.php:57}() /vagrant/platproc/vendor/yiisoft/yii2/base/InlineAction.php:57
PHP  10. yii\apidoc\commands\ApiController->actionIndex() /vagrant/platproc/vendor/yiisoft/yii2/base/InlineAction.php:57
PHP  11. yii\apidoc\commands\ApiController->loadContext() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/commands/ApiController.php:76
PHP  12. unserialize() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/components/BaseController.php:119
PHP  13. spl_autoload_call() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/components/BaseController.php:119
PHP  14. yii\BaseYii::autoload() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/components/BaseController.php:119
PHP  15. include() /vagrant/platproc/vendor/yiisoft/yii2/BaseYii.php:293
PHP  16. spl_autoload_call() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/models/ClassDoc.php:18
PHP  17. yii\BaseYii::autoload() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/models/ClassDoc.php:18
PHP  18. include() /vagrant/platproc/vendor/yiisoft/yii2/BaseYii.php:293
PHP  19. spl_autoload_call() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/models/TypeDoc.php:26
PHP  20. yii\BaseYii::autoload() /vagrant/platproc/vendor/yiisoft/yii2-apidoc/models/TypeDoc.php:26
Error: Cannot use yii\base\Object as Object because 'Object' is a special class name

**Comment by ricpelo** [comment]
Probably related to #163 .

**Comment by cebe** [comment]
>  composer update with * (branch master) not working, only with tags.

going to make a release now.
