### ISSUE TITLE
PDF generator has problems with non-ASCII in code tags

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2-apidoc#170]
### What steps will reproduce the problem?

Check for example the russian guide:

This line:

https://github.com/yiisoft/yii2/commit/03de28b2755ec39f40c7eb5f326f4a8609dba9ae#diff-427d477c95eef73b208a4b06d35f96c4R97

is rendered like this:

![bildschirmfoto von 2018-09-21 10-15-17](https://user-images.githubusercontent.com/189796/45868934-52ab6900-bd87-11e8-9a49-0e042c5dbf00.png)

in the [russian guide PDF file](https://www.yiiframework.com/doc/download/yii-guide-2.0-ru.pdf).

### What's expected?

proper rendering (correct URL) like in HTML guide and english PDF.

### What do you get instead?

see above.

### Additional info

This seems to be a problem with LaTeX, lstlisting environment and UTF8 characters:

https://tex.stackexchange.com/questions/24528/having-problems-with-listings-and-utf-8-can-it-be-fixed#24532

**Comment by arogachev** [comment]
After switching from `listings` to `minted` (#134) this problem is gone.
