### ISSUE TITLE
Yii 2.0.16

### ISSUE THREAD

**Issue by Inkognitoo** [yiisoft/yii2-apidoc#175]
### What steps will reproduce the problem?
Create Yii 2.0.16 project and try install last yii2-apidoc library

### What's expected?
Successful install

### What do you get instead?
Error:
```
  Problem 1
    - yiisoft/yii2-apidoc 2.1.0 requires cebe/markdown ~1.0.0 | ~1.1.0 -> satisfiable by cebe/markdown[1.0.x-dev].
    - yiisoft/yii2-apidoc 2.1.1 requires cebe/markdown ~1.0.0 | ~1.1.0 -> satisfiable by cebe/markdown[1.0.x-dev].
    - yiisoft/yii2-apidoc 2.1.x-dev requires cebe/markdown ~1.0.0 | ~1.1.0 -> satisfiable by cebe/markdown[1.0.x-dev].
    - Conclusion: don't install cebe/markdown 1.0.x-dev
    - Installation request for yiisoft/yii2-apidoc ^2.1 -> satisfiable by yiisoft/yii2-apidoc[2.1.0, 2.1.1, 2.1.x-dev].
```

I think it because Yii 2.0.16 require (https://github.com/yiisoft/yii2/blob/2.0.16/framework/UPGRADE.md#upgrade-from-yii-2015) 1.2.x `cebe/markdown` version, but yii2-apidoc 2.1.1 want `~1.0.0 | ~1.1.0`

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.16
| Yii APIDoc version | 2.1.1
| PHP version        | 7.2
| Operating system   | Ubuntu

**Comment by samdark** [comment]
Thanks for reporting. Updated constraint in composer.json.
