### ISSUE TITLE
apidoc does not handle php 7.x features

### ISSUE THREAD

**Issue by ancpru** [yiisoft/yii2-apidoc#178]
Currently APIDOC mostly ignores PHP 7.x features like declared return types or failes parsing code containing them. 

Reason: The used phpdocumentor/reflection version do not support them.

(NOTE: I am working on a port to phpdocumentor/reflection 4.0 - I entered this issue to have issue ID)

| Q                  | A
| ------------------ | ---
| Yii APIDoc version | 2,1
| PHP version        | 7.2
| Operating system   | Linux

**Comment by machour** [comment]
There's already #163 unless I'm missing something
