### ISSUE TITLE
Incorrect output when typehinting a variable as string

### ISSUE THREAD

**Issue by YiiRocks** [yiisoft/yii2-apidoc#179]
### What steps will reproduce the problem?
Running api docs for typehinted code:
```
/**
 * Returns the ActiveField inputTemplate.
 * @param string $name Name of the icon
 * @param array $options Optional options for the field and the icon
 * @return string ActiveField icon with proper code
 */
public function activeFieldAddon(string $name, array $options = []): string {
	//code here
}
```

### What's expected?

| public string activeFieldAddon ( string $name, array $options = [] ) |  |  |
|-------------------------------------------------------------------------------------------|--------|---------------------------------------------|
| $name | string | Name of the icon |
| $options | array | Optional options for the field and the icon |
| return | string | ActiveField icon with proper code |

### What do you get instead?

| public string activeFieldAddon ( \thoulah\fontawesome\string $name, array $options = [] ) |  |  |
|-------------------------------------------------------------------------------------------|--------|---------------------------------------------|
| $name | string | Name of the icon |
| $options | array | Optional options for the field and the icon |
| return | string | ActiveField icon with proper code |

### Additional info

| Q                  | A
| ------------------ | ---
| Yii version         | 2.0.21
| Yii APIDoc version | 2.1.1
| PHP version        | 7.2.19
| Operating system   | Linux Mint

**Comment by samdark** [comment]
Likely it should be fixed by upgrading `phpdocumentor/reflection`.

**Comment by samdark** [comment]
See #146
