### ISSUE TITLE
404 error "All Classes", template=online

### ISSUE THREAD

**Issue by YiiRocks** [yiisoft/yii2-apidoc#180]
### What steps will reproduce the problem?
Create api doc with template online, display inside yii2.
Click "All Classes" link on top of any page ([example here](https://www.yiiframework.com/doc/api/2.0/yii-base-action)).

### What's expected?
https://www.yiiframework.com/doc/api/2.0/index

### What do you get instead?
https://www.yiiframework.com/doc/api/2.0/index.html
![404](https://www.yiiframework.com/image/404.jpg)

### Additional info
Possibly a bug in https://github.com/yiisoft-contrib/yiiframework.com, perhaps in the template `online`. As I thought the template might be the issue, I report bug here.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/issues/386

**Comment by samdark** [comment]
It is a template issue, indeed,
