### ISSUE TITLE
Cant not install 

### ISSUE THREAD

**Issue by ezsky** [yiisoft/yii2-apidoc#183]
Problem 1
    - Installation request for yiisoft/yii2-apidoc dev-master -> satisfiable by yiisoft/yii2-apidoc[dev-master].
    - Conclusion: remove cebe/markdown 1.2.1
    - Conclusion: don't install cebe/markdown 1.2.1
    - yiisoft/yii2-apidoc dev-master requires cebe/markdown-latex ~1.0 -> satisfiable by cebe/markdown-latex[1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5].
    - cebe/markdown-latex 1.0.0 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.0 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.1 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.2 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.3 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.4 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.5 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - Can only install one of: cebe/markdown[1.0.0, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.1, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.2, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.3, 1.2.1].
    - Installation request for cebe/markdown (locked at 1.2.1) -> satisfiable by cebe/markdown[1.2.1].

**Comment by samdark** [comment]
How do you install it exactly?

**Comment by ezsky** [comment]
> How do you install it exactly?

no, I had create new basic template and use default composer install command.
but, yii2-doc 2.1.2 can not install

**Comment by hi-rad** [comment]
I have got the same problem
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install yiisoft/yii2-apidoc 2.1.2
    - Conclusion: don't install yiisoft/yii2-apidoc 2.1.1
    - Conclusion: remove cebe/markdown 1.2.1
    - Installation request for yiisoft/yii2-apidoc ^2.1 -> satisfiable by yiisoft/yii2-apidoc[2.1.0, 2.1.1, 2.1.2].
    - Conclusion: don't install cebe/markdown 1.2.1
    - yiisoft/yii2-apidoc 2.1.0 requires cebe/markdown ~1.0.0 | ~1.1.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2].
    - Can only install one of: cebe/markdown[1.0.0, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.1, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.2, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.3, 1.2.1].
    - Can only install one of: cebe/markdown[1.1.0, 1.2.1].
    - Can only install one of: cebe/markdown[1.1.1, 1.2.1].
    - Can only install one of: cebe/markdown[1.1.2, 1.2.1].
    - Installation request for cebe/markdown (locked at 1.2.1) -> satisfiable by cebe/markdown[1.2.1].


Installation failed, reverting ./composer.json to its original content.

```

**Comment by shouhuori** [comment]
same problem

**Comment by samdark** [comment]
Yes, that's because https://github.com/cebe/markdown-latex/issues/14.

**Comment by hooman-pro** [comment]
so I have same problem: 




$ composer require --prefer-dist yiisoft/yii2-apidoc "*"
./composer.json has been updated
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)
                                                                                Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install yiisoft/yii2-apidoc 2.1.3
    - Conclusion: don't install yiisoft/yii2-apidoc 2.1.2
    - Conclusion: don't install yiisoft/yii2-apidoc 2.1.1
    - Conclusion: don't install yiisoft/yii2-apidoc 2.1.0
    - Conclusion: don't install yiisoft/yii2-apidoc 2.0.6
    - yiisoft/yii2-apidoc 2.0.1 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.2 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.3 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.4 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.5 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - Conclusion: don't install cebe/markdown-latex 1.0.0
    - Conclusion: remove cebe/markdown 1.2.1
    - Installation request for yiisoft/yii2-apidoc * -> satisfiable by yiisoft/yii2-apidoc[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1, 2.1.2, 2.1.3].
    - Conclusion: don't install cebe/markdown 1.2.1
    - yiisoft/yii2-apidoc 2.0.0 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - Can only install one of: cebe/markdown[1.0.0, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.1, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.2, 1.2.1].
    - Can only install one of: cebe/markdown[1.0.3, 1.2.1].
    - Installation request for cebe/markdown (locked at 1.2.1) -> satisfiable by cebe/markdown[1.2.1].


Installation failed, reverting ./composer.json to its original content.


$  composer why-not cebe/markdown
yiisoft/yii2  2.0.32  requires  cebe/markdown (~1.0.0 | ~1.1.0 | ~1.2.0)


$ composer why cebe/markdown-latex


  [InvalidArgumentException]
  Could not find package "cebe/markdown-latex" in your project


depends [-r|--recursive] [-t|--tree] [--] <package> [<constraint>]


$ composer why-not cebe/markdown-latex


  [InvalidArgumentException]
  Could not find package "cebe/markdown-latex" in your project


prohibits [-r|--recursive] [-t|--tree] [--] <package> [<constraint>]








what should I do? 
I should only wait for new version of cebe/markdown? 
or it have solution؟

**Comment by bizley** [comment]
Duplicates #123
