### ISSUE TITLE
Request - Generate private methods/properties documentation

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2-apidoc#184]
This is a good PHP documentation generator. It is simple and easy to use.

A suggest is to generate the documentation for private methods and properties.

**Comment by samdark** [comment]
Why do you need private properties documented?

**Comment by neoacevedo** [comment]
Shared documentation. As the public and protected properties, the 
private properties documentation should be also documented, except if 
the getter and setter methods are configured.

**Comment by samdark** [comment]
But isn't it useless? You can't access private property in any way.

**Comment by neoacevedo** [comment]
Yes, forget it about private properties documentation. I was lost in 
this. The private methods should be documented. More than access or not 
via IDE code, the documentation for this is useful for knowledge 
transference or only to remember to myself its functionality.

**Comment by samdark** [comment]
That's the same as properties. These are generally not that useful in terms of reading them out of context.

**Comment by arogachev** [comment]
I think we should close this since it was decided not to implement it. Especially after this decision https://github.com/yiisoft/yii2-apidoc/issues/221#issuecomment-964887544. @samdark What do you think? :thinking:

**Comment by samdark** [comment]
Yes, should be closed since private things are implementation detail and not part of the API.
