### ISSUE TITLE
how document db filed

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2-apidoc#191]
Hi 
excuse me I have a  question
when I generate a model extent active record, that model have magic fileds . they are database fileds.
how can i write php comment for these filed? apidoc read them and generate document for theme?

**Comment by hooman-pro** [comment]
/**
 * This is the model class for table "tbl_question".
 *
 * @property string $id
 * @property string $unique_id
 * @property string $title
*/

it seems api doc remove all @property ....

**Comment by rob006** [comment]
Is it `@Property` or `@property`?

**Comment by hooman-pro** [comment]
lower case is correct.

**Comment by hooman-pro** [comment]
@samdark 
can you answer me, please ?
how can I write document for database filed such as 
post model have id, title, content, image .... filed

**Comment by samdark** [comment]
I don't know, will try it after making next release of Yii 2 and some things on Yii 3.

**Comment by samdark** [comment]
Verified that it still doesn't work. See #7, #132.

**Comment by samdark** [comment]
Please test if https://github.com/yiisoft/yii2-apidoc/pull/192 works for you.

**Comment by hooman-pro** [comment]
Yes it works. Thank you!
