### ISSUE TITLE
Add link to phpdocumentor markdown documentation on readme.md

### ISSUE THREAD

**Issue by markch123** [yiisoft/yii2-apidoc#193]
I believe apidoc uses phpdocumentor to generate docs? If yes it would be very useful to add a link at the top of readme.md directing them to their site and markdown descriptions/examples. Something like...

"ApiDoc uses phpdocumentor to generate documentation. For more details on the markdown syntax plus examples please refer to <link to phpdocumentor api docs>".

**Comment by samdark** [comment]
Good idea.
