### ISSUE TITLE
No inline link with {@link}

### ISSUE THREAD

**Issue by nilsburg** [yiisoft/yii2-apidoc#196]
### What steps will reproduce the problem?
Create a method and use inline link with {@link Class:Method} in the docblock
### What's expected?
To see a link in the generated documentation to the linked method
### What do you get instead?
Plain text
Although PHPStorm shows the block with the link
![apidoc1](https://user-images.githubusercontent.com/1023621/81822608-a27a0d80-9533-11ea-9c0e-2d45a9e47124.png)
![apidoc2](https://user-images.githubusercontent.com/1023621/81822761-cccbcb00-9533-11ea-8aed-304a059cc48f.png)

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.35
| Yii APIDoc version | 2.1.4
| PHP version        |7.3.1
| Operating system   |Windows 10

**Comment by samdark** [comment]
Yii was using their own format, `[[ClassName]]`. phpdoc standard one isn't implemented.
