### ISSUE TITLE
default link in docs/guide shows 404

### ISSUE THREAD

**Issue by cgsmith** [yiisoft/yii2-apidoc#197]
### What steps will reproduce the problem?
1. Navigate here: https://www.yiiframework.com/doc/guide/2.0/en/input-validation#data-filtering
2. Click on `default` link.
3. Receive 404

### What is the expected result?
Navigate to default core validator page

### What do you get instead?
404

### Additional info

This happens on @cebe mirror as well http://stuff.cebe.cc/yii2docs/guide-input-validation.html

Any guide on how the docs are generated? All links look correct just isn't rendering the link correctly.

| Q                | A
| ---------------- | ---
| Yii version      | `master` and `2.0.12.1`
| PHP version      | n/a
| Operating system | n/a

**Comment by arogachev** [comment]
> @SOHELAHMED7 I thought the same thing about dropping the `.md` but other places in the docs have it. There is something else causing this that I'm not aware of yet.

`.md` part is removed for each link during guide generation. The bug occurs when block contains multiple links, only the first one is processed correctly.

Fixed in https://github.com/yiisoft/yii2-apidoc/pull/220/commits/5b2f0b71a784165175e1c44375fe3694e807e159, also I improved implementation.
