### ISSUE TITLE
Не генерируются файлы для классов в которых есть обнуляемые типы переменных

### ISSUE THREAD

**Issue by sallfris** [yiisoft/yii2-apidoc#199]
### What steps will reproduce the problem?
1) Создать класс в папке `controllers`  с `action` возвращающим обнуляемое значение
```
/**
 * Class DefaultController
 * @package rest\modules\city\controllers
 */
class DefaultController extends yii\rest\Controller
{
    /**
     * `GET city/index` - Список городов
     * @return CityList[]|null Возвращает список городов
     */
    public function actionIndex(): ?array
```
2) Запустить генерацию `vendor/bin/apidoc api rest rest/docs/api/`
### What's expected?
Файл `rest\docs\api\rest-modules-city-controllers-defaultcontroller.html` с описанием контроллера
### What do you get instead?
Файл не создается

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.37 
| Yii APIDoc version | 2.1.5
| PHP version        | 7,4
| Operating system   | Linux

**Comment by samdark** [comment]
Есть идеи почему?

**Comment by samdark** [comment]
Вероятно, проблема в использовании старой версии парсера...
