### ISSUE TITLE
Processing files... 0% (0/1) ETA: n/a   Error: Undefined variable: output

### ISSUE THREAD

**Issue by gaohongli001** [yiisoft/yii2-apidoc#200]
### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         |
| Yii APIDoc version |
| PHP version        |
| Operating system   |

**Comment by gaohongli001** [comment]
vendor/bin/apidoc api ./commands .out
TargetDirectory already exists. Overwrite? (yes|no) [yes]:y
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
1 file to update.
Processing files... 0% (0/1) ETA: n/a   Error: Undefined variable: output


what happened?

**Comment by gaohongli001** [comment]
vendor/bin/apidoc api ./commands .out
TargetDirectory already exists. Overwrite? (yes|no) [yes]:y
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
1 file to update.
Processing files... 0% (0/1) ETA: n/a Error: Undefined variable: output

what happened?

**Comment by samdark** [comment]
What were the files you ran it on? Can you share these?
