### ISSUE TITLE
Fix PHP 8 compatibility

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-apidoc#203]
Currently tests are failing on PHP 8 (should be enabled in the matrix, https://github.com/yiisoft/yii2-apidoc/blob/master/.github/workflows/build.yml). Needs to be fixed.

**Comment by gomasmile** [comment]
Hi, what does it look like when will php 8 support?

**Comment by samdark** [comment]
@gomasmile noone is active working on it at the moment. If you want, you can try fixing it and send a pull request.
