### ISSUE TITLE
Issue installing yii2-apidoc via composer

### ISSUE THREAD

**Issue by markch123** [yiisoft/yii2-apidoc#208]
I'm trying to install yii2-apidoc via composer and it fails complaining about a conflict with phpdocumentor/reflection-docblock. The Readme mentions there are conflicts, but I think these might be new ones?

### What steps will reproduce the problem?

`` 
$ composer create-project --prefer-dist yiisoft/yii2-app-basic basic
``

add "yiisoft/yii2-apidoc": "~2.1.0" to composer.json

``
$ composer update yiisoft/yii2-apidoc --with-all-dependencies
``

  Problem 1
    - codeception/verify is locked to version 1.1.0 and an update of this package was not requested.
    - Conclusion: don't install phpdocumentor/reflection-docblock 2.0.5 (conflict analysis result)
    - yiisoft/yii2-apidoc[2.1.0, ..., 2.1.6] require phpdocumentor/reflection-docblock ^2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4, 2.0.5].
    - Conclusion: don't install phpdocumentor/reflection-docblock 2.0.4 (conflict analysis result)
    - Root composer.json requires yiisoft/yii2-apidoc ~2.1.0 -> satisfiable by yiisoft/yii2-apidoc[2.1.0, ..., 2.1.6]. 

### What's expected?

It installs.

### What do you get instead?

Conflicts.

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | Latest
| Yii APIDoc version | Latest
| PHP version        | 7.4
| Operating system   |

**Comment by bizley** [comment]
Codeception requires phpunit that requires phpspec/prophecy that requires phpdocumentor/reflection-docblock in recent version while yiisoft/yii2-apidoc requires an old version so you cannot have both at the same time, sorry.

**Comment by markch123** [comment]
Cheers for quick response!

Maybe a small note in the ReadMe to help others?

**Comment by bizley** [comment]
Hmm, I'm not sure where and what to write. There might be a bunch of packages that conflicts with `yii2-apidoc` simply because it's quite old software now...

**Comment by markch123** [comment]
Is there plans to move this across with yii3?

**Comment by bizley** [comment]
@samdark is the best person to answer that.

**Comment by markch123** [comment]
BTW: thanks to your pointer I managed to get it to install. I then had a play with the yii2-apidoc composer.json and ended up with this. 

    "require": {
        "php": ">=5.4",
        "yiisoft/yii2": "~2.0.13",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "phpdocumentor/reflection": "^5.0.1",
        "phpdocumentor/reflection-docblock": "^5.0.0",
        "nikic/php-parser": "^4.0",
        "cebe/js-search": "~0.9.3",
        "cebe/markdown": "~1.0.0 | ~1.1.0 | ~1.2.0",
        "cebe/markdown-latex": "~1.0",
        "scrivo/highlight.php": "~9.13"
    },

After a composer upgrade,  I ran `apidoc` against my markdown and it seems to work. Not sure if I've made a mistake along the line i.e running wrong version, which is highly likely :)

**Comment by bizley** [comment]
You should not modify files in the vendor folder, and if I remember correctly that package was not compatible with latest `reflection` so I'm impressed that it worked 😄
