### ISSUE TITLE
todo tag not rendered in the documentation

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2-apidoc#209]
The todo tag isn't being rendered in the main docblocks. 

For instance:
```php
 /**
   * Foo method.
   * @param \Illuminate\Http\Request
   * @param foo
   * @todo Whatever
   * @return \Illuminate\Http\Response
   */
 public function foo($foo) ...
```
When the docblock is rendered, the description, params and return are rendered except the todo tag, no matter if I put behind the description, behind the return statement.

**Comment by bizley** [comment]
I'm not sure if this package renders it at all. Can someone confirm either way?

**Comment by samdark** [comment]
Nope, it does not. Could be useful for user-generated docs though.
