### ISSUE TITLE
Error: Getting unknown property: yii\apidoc\models\InterfaceDoc::parentClass

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2-apidoc#210]
When i run the console command to generate a json version of the docs i get:

```
Error: Getting unknown property: yii\apidoc\models\InterfaceDoc::parentClass
```

the sh file

```sh
#!/bin/sh

LUYA=vendor/luyadev/luya/core
ADMIN=vendor/luyadev/luya-module-admin/src
CMS=vendor/luyadev/luya-module-cms/src
SUITE=vendor/luyadev/luya-testsuite
YII=vendor/yiisoft/yii2
HELPERS=vendor/luyadev/yii-helpers/src
OUTPUT=data

./vendor/bin/apidoc api $LUYA,$ADMIN,$CMS,$YII,$SUITE,$HELPERS $OUTPUT --interactive=0 --template=json
```

Could not dig deeper but, it seems the process ends afterwards.

**Comment by samdark** [comment]
What PHP version is that?

**Comment by nadar** [comment]
sorry for not providing that, `PHP 7.2.24-0ubuntu0.18.04.8 (cli) (built: Jul  5 2021 17:41:32) ( NTS )`

**Comment by nadar** [comment]
Same problem with 7.4 (`PHP 7.4.16 (cli) (built: Jul  5 2021 13:04:38) ( NTS )` could you suggest me what to fix, so i can send a PR? We are unable to update our luya.io api docs anymore.

**Comment by bizley** [comment]
I'm working on updated version but no ETA yet.

**Comment by nadar** [comment]
Is there a quick fix available? like `change XYZ to ZXYZ` in `vendor/yiisoft/...` so we could at least generate the docs for now?

**Comment by bizley** [comment]
Let me check, will get back to it later on today.

**Comment by samdark** [comment]
@nadar roll back PHP version for docs generation. That's a quick fix that doesn't require code changes.

**Comment by samdark** [comment]
btw., do you have a public set of docs/scripts we can test on?

**Comment by nadar** [comment]
@samdark rollback to which version, 7.0 i assume? I can prepare something if you like, sure :+1:

**Comment by samdark** [comment]
Yes. 7.0 worked for sure.

Preparing a project that fails and is launched by a single command would be good for testing, I think. @bizley anything else @nadar can do to help?

**Comment by bizley** [comment]
Yes, a problematic file/files to put my hands on would be great.

**Comment by samdark** [comment]
@brandonkelly would be great to get your set as well.

**Comment by brandonkelly** [comment]
@samdark Just invited you to it (private repo). Our issue is with _parsing_ PHP 7.2 code though; we don’t care which version we have to run it with.

**Comment by samdark** [comment]
@brandonkelly would you please invite @bizley as well?

**Comment by nadar** [comment]
This should throw the error:

```sh
#!/bin/sh

git clone git@github.com:luyadev/luya-kickstarter.git

cd luya-kickstarter

composer install
composer require luyadev/luya:^2.0 --update-with-all-dependencies
rm -rf composer.lock
composer require yiisoft/yii2-apidoc:^2.0 --update-with-all-dependencies

rm -rf vendor/yiisoft/yii2/base/Object.php

LUYA=vendor/luyadev/luya/core
ADMIN=vendor/luyadev/luya-module-admin/src
CMS=vendor/luyadev/luya-module-cms/src
SUITE=vendor/luyadev/luya-testsuite
YII=vendor/yiisoft/yii2
HELPERS=vendor/luyadev/yii-helpers/src
OUTPUT=data

./vendor/bin/apidoc api $LUYA,$ADMIN,$CMS,$YII,$SUITE,$HELPERS $OUTPUT --interactive=0 --template=json
```

At the end you have `Error: Getting unknown property: yii\apidoc\models\InterfaceDoc::parentClass` while generating your also able to see the other error, mentioned in issues:

![image](https://user-images.githubusercontent.com/3417221/128142593-02e0c91e-1a48-4614-bc2c-8e1ba8e10de1.png)

**Comment by brandonkelly** [comment]
@samdark @bizley Added

**Comment by bizley** [comment]
@nadar so far I've found that in `luya\admin\ngrest\NgRestButtonConditionInterface:22` there is rather invalid `@inheritdoc` tag which triggers methods in apidoc that are not ready to handle it which of course is a bug anyway but that is the reason.

**Comment by bizley** [comment]
I've come up with a fix although - is this an "ok" result? ;)

![image](https://user-images.githubusercontent.com/8577314/129451916-a37aa5e4-c7ec-4dc8-a109-c812c139aad7.png)

**Comment by nadar** [comment]
Thanks @bizley. Yes, everything that finishes the docs and generating an output is a good result in this case :-)

**Comment by samdark** [comment]
@nadar the fix is merged. Please check how it works now.

**Comment by bizley** [comment]
@brandonkelly I'm afraid I cannot give you such easy solution, I still work on a new version, that will handle PHP7.2+ code specific things.

**Comment by arogachev** [comment]
> @brandonkelly I'm afraid I cannot give you such easy solution, I still work on a new version, that will handle PHP7.2+ code specific things.

https://github.com/yiisoft/yii2-apidoc/pull/220

But what about the current issue? Seems like it's solved, isn't it?

**Comment by bizley** [comment]
Yes, it's fixed.
