### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2-apidoc#214]
### What steps will reproduce the problem?
Run composer command to install:
`composer require --dev yiisoft/yii2-apidoc:~2.1.0`
### What's expected?
To install in dev, yii2-apidoc
### What do you get instead?
```sh
Running composer update yiisoft/yii2-apidoc
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-apidoc[2.1.0, ..., 2.1.6] require phpdocumentor/reflection-docblock ^2.0.4 -> found phpdocumentor/reflection-docblock[2.0.4, 2.0.5] but the package is fixed to 5.2.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.    
    - Root composer.json requires yiisoft/yii2-apidoc ~2.1.0 -> satisfiable by yiisoft/yii2-apidoc[2.1.0, ..., 2.1.6].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.43
| Yii APIDoc version | ~2.1.0
| PHP version        | 8.0
| Operating system   | openSUSE TW with Docker

**Comment by bizley** [comment]
As you can read in the error message you already have `phpdocumentor/reflection-docblock` installed with higher version than yii2-apidoc allows.

**Comment by neoacevedo** [comment]
@bizley Yes, I know, but it comes from yiiisoft/yii2, so, it's not my error itself.

**Comment by bizley** [comment]
On the clean installation as suggested by the project, there is the conflict with `codeception`. Until `apidoc` is updated you need to remove `codeception` package if you want to have the former.
