### ISSUE TITLE
Links to private methods are broken

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2-apidoc#221]
### What steps will reproduce the problem?

- https://github.com/yiisoft/yii2/blob/53477e8ad9bd782600f6a8144b4806bb07a4c69b/framework/helpers/BaseHtml.php#L2016
- https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#addCssClass()-detail

### What's expected?

Link.

### What do you get instead?

Text.

### Additional info

We should either use link or do not render it at all.  Related: https://github.com/yiisoft/yii2-apidoc/issues/184.

| Q                  | A
| ------------------ | ---
| Yii vesion         | 
| Yii APIDoc version | 
| PHP version        | 
| Operating system   |

**Comment by samdark** [comment]
I think it should not be rendered and actually we should remove such references from out phpdoc.

**Comment by samdark** [comment]
Nothing to be fixed in apidoc but a pull request to yii2 repo is welcome.

**Comment by arogachev** [comment]
Fixed in https://github.com/yiisoft/yii2/pull/19010.
