### ISSUE TITLE
conflicting cebe/markdown with yii2-app-basic

### ISSUE THREAD

**Issue by xwiggen** [yiisoft/yii2-apidoc#24]
Latest yii2-app-basic (2.0.6, 2015-09-30) has dependency on cebe/markdown 1.1.0 in composer.lock.
This conflicts with yii2-apidoc (cebe/markdown-latex), unable to install through composer.

    composer create-project --prefer-dist yiisoft/yii2-app-basic basic
    cd basic
    composer require --prefer-dist yiisoft/yii2-apidoc 

Result:
    Problem 1
    - Installation request for cebe/markdown == 1.1.0.0 -> satisfiable by cebe/markdown[1.1.0].
    - yiisoft/yii2-apidoc 2.0.0 requires cebe/markdown-latex * -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.1 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.2 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.3 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.4 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - Conclusion: don't install cebe/markdown-latex 1.0.0
    - Installation request for yiisoft/yii2-apidoc ^2.0 -> satisfiable by yiisoft/yii2-apidoc[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].

**Comment by xwiggen** [comment]
workaround;

Adding 
 "yiisoft/yii2-apidoc": "~2.0.0" 
to composer.json manually and then
 composer update
works

**Comment by Olegf13** [comment]
It gets an error with `Yii2 advanced` too. See details below.

_composer require --dev --prefer-dist yiisoft/yii2-apidoc:^2.0_

```
Using version ^2.0 for yiisoft/yii2-apidoc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cebe/markdown == 1.1.0.0 -> satisfiable by cebe/markdown[1.1.0].
    - yiisoft/yii2-apidoc 2.0.0 requires cebe/markdown-latex * -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.1 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.2 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.3 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - yiisoft/yii2-apidoc 2.0.4 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - Conclusion: don't install cebe/markdown-latex 1.0.0
    - Installation request for yiisoft/yii2-apidoc ^2.0 -> satisfiable by yiisoft/yii2-apidoc[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by hezll** [comment]
I still got the same problems with yii 2.0.8 and php7

**Comment by cebe** [comment]
see updated installation docs: https://github.com/yiisoft/yii2-apidoc#installation
