### ISSUE TITLE
(PDF guide) On each even page content is slightly shifted to the right

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2-apidoc#249]
### What steps will reproduce the problem?

Download [PDF guide](https://www.yiiframework.com/doc/download/yii-guide-2.0-en.pdf) or generate it.

### What's expected?

The same indentation on each page.

### What do you get instead?

Different indentation on odd and even pages.

### Additional info

| Q                  | A
| ------------------ | ---
| Yii version         | doesn't matter
| Yii APIDoc version | doesn't matter
| PHP version        | doesn't matter
| Operating system   | doesn't matter

Maybe this is by design? :thinking: Would like to know more details and history behind it. But overall it's acceptable and not a high priority right now.

**Comment by samdark** [comment]
@cebe anything about the topic you can remember?

**Comment by samdark** [comment]
Cool. Wasn't aware of it. Thanks.

**Comment by arogachev** [comment]
@rob006 Hi. Thanks for shedding light on this. What about odd pages though? Do they also have according margin?

Also I'm pretty sure that majority of people use it without printing. So maybe it's nice to have option for disabling this behavior.

**Comment by arogachev** [comment]
@cebe Got i, good to know. Closing then.
