### ISSUE TITLE
markdown to html rendering tags are disappeared

### ISSUE THREAD

**Issue by almaz-free** [yiisoft/yii2-apidoc#257]
Found, that in file
https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/test-environment-setup.md
has code example:
```
<VirtualHost *:80>
    DocumentRoot "path/to/basic/web"
...
```
but in html version first string are disappeared:
https://www.yiiframework.com/doc/guide/2.0/ru/test-environment-setup

**Comment by arogachev** [comment]
Thanks. Turns out it's not yii2-apidoc issue. But I decided to not move it to yii2 repo because of a quick fix.
