### ISSUE TITLE
inheritdoc does not work on properties

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2-apidoc#27]
This: https://github.com/yiisoft/yii2/blob/master/framework/rbac/Item.php#L22

should be inherited by these:

https://github.com/yiisoft/yii2/blob/master/framework/rbac/Role.php#L17
https://github.com/yiisoft/yii2/blob/master/framework/rbac/Permission.php#L17

But the documentation ends up being empty: http://www.yiiframework.com/doc-2.0/yii-rbac-role.html#properties

**Comment by cebe** [comment]
should be fixed by https://github.com/yiisoft/yii2-apidoc/commit/bab23f2bd7393345dd7b285f41bbbc518e9ecf76

**Comment by nkovacs** [comment]
This looks broken, the documentation is inherited twice:

http://www.yiiframework.com/doc-2.0/yii-rest-controller.html#$enableCsrfValidation-detail

**Comment by cebe** [comment]
@nkovacs can you please open a new issue for that?

**Comment by nkovacs** [comment]
Sure, here it is: #61
