### ISSUE TITLE
Support ePub

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2-apidoc#270]
Extracted from https://github.com/yiisoft-contrib/yiiframework.com/issues/13#issuecomment-96422092.
Suggested by @iJackUA.

ePub looks interesting though. But again we should rely on users' demand. Have they asked about it? @samdark And how often (comparing to CHM)?

Not a high priority currently.

**Comment by samdark** [comment]
Nope, noone asked about it so far.

**Comment by arogachev** [comment]
OK, so I guess we won't be implementing this.
