### ISSUE TITLE
api is generating with errors

### ISSUE THREAD

**Issue by Nosthertus** [yiisoft/yii2-apidoc#28]
i installed manually `composer create-project --prefer-dist yiisoft/yii2-apidoc yii2 2.0.0`, it downloads all pretty well.

but then when i generate the api with this command 
`yii2/apidoc api yii2 ./output`

it throws this message
```
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
39 files to update.
Processing files... done.(39/39) ETA: 0 sec.
Updating cross references and backlinks... done.
Rendering files: done.(40/40) ETA: 0 sec.
generating extension index files...done.
generating search index...done.
202 errors have been logged to ./output/errors.txt
```
you can check the file in [here] (http://pastebin.com/WRSX8xyQ)

this command is ran under windows 10 cmd

**Comment by cebe** [comment]
these errors are about the api documentation, the command ran just fine.
the file contains problems with the PHPdoc annotations that need to be fixed.

**Comment by Nosthertus** [comment]
i even checked the index file and no class was in it, although i was able to get the right documentation by changing the source to an existing yii2 project directory
