### ISSUE TITLE
Tables have no spacing

### ISSUE THREAD

**Issue by tehmaestro** [yiisoft/yii2-apidoc#29]
Hi, I trying to create some tables, but there's no border and no spacing on the cells. Am I missing something? Thanks.

```
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell
```

**Comment by cebe** [comment]
by default tables seem to have no style. we could adjust the markdown parser to add bootstrap classes by default.

**Comment by phpyii** [comment]
+1

**Comment by cebe** [comment]
anyone willing to send a pull request?

As far as I see this could be added by extending the method [`renderTable()`](https://github.com/cebe/markdown/blob/e2a490ceec590bf5bfd1b43bd424fb9dceceb7c5/block/TableTrait.php#L86) in https://github.com/yiisoft/yii2-apidoc/blob/master/helpers/ApiMarkdown.php

with something like `str_replace('<table>', '<table class="table table-bordered">', parent::renderTable(...))`

**Comment by cebe** [comment]
fixed.
