### ISSUE TITLE
PHP 8.2 not supportet yet

### ISSUE THREAD

**Issue by ondics** [yiisoft/yii2-apidoc#297]
I built my Docker image using `FROM php:8.2-bullseye`.

When executing 

    ./vendor/bin/apidoc api controllers/api ./web/apidoc

the result is:

    TargetDirectory already exists. Overwrite? (yes|no) [yes]:yes
    Error: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated

When building the image using `FROM php:8.0-bullseye` apidoc page creation works.

The supported PHP versions should be mentioned in the README.md

**Comment by mtangoo** [comment]
Up to now PHP supported is up to 8.1
Support for 8.2 was merged but not released yet. So use "dev-master" if you are willing to keep up with any breaking changes. I use it in development and have not found any issue yet

**Comment by mtangoo** [comment]
Ignore my previous (and deleted) comment.
Yii support PHP8.2 with 2.0.48 version.
Please update your composer
https://github.com/yiisoft/yii2/releases/tag/2.0.48
