### ISSUE TITLE
interface documentation does not show inheritance

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2-apidoc#3]
For example, `ActiveQueryInterface` extends `QueryInterface`, but [its documentation](http://www.yiiframework.com/doc-2.0/yii-db-activequeryinterface.html) does not mention this (in the table at the top), and it does not list the inherited methods.

**Comment by cebe** [comment]
fixed, thanks for reporting! website will take a bit to get updated.

**Comment by nkovacs** [comment]
Shouldn't the label be "Extends"?

**Comment by cebe** [comment]
Yeah, right. fixed. Thanks!
