### ISSUE TITLE
Code block is broken in GFM in particular case

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-apidoc#32]
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-query-builder.md#yiidbqueryorderbyorderby-

http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#order-by

In our rendered version code block is broken.

**Comment by cebe** [comment]
fixed here: http://stuff.cebe.cc/yii2docs/guide-db-query-builder.html#order-by
changes should propagete to yiiframework.com soon.

**Comment by samdark** [comment]
Great.
