### ISSUE TITLE
URL with anchor scrolls too far

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2-apidoc#33]
Try to open any link with anchor to a method/property and you'll find, that the page scrolls to the anchor, but the navigation bar is fixed and overlaps the beginning of the documentation block:
http://www.yiiframework.com/doc-2.0/yii-base-event.html#off()-detail

**Comment by SilverFire** [comment]
May be fixed somehow like this:
http://stackoverflow.com/questions/27096621/how-to-disable-anchor-jump-when-loading-a-page/29823834#29823834

**Comment by cebe** [comment]
works for me in  Firefox 

![bildschirmfoto von 2015-12-23 19 01 16](https://cloud.githubusercontent.com/assets/189796/11981971/b6b8cf92-a9a7-11e5-9573-af440681bd8d.png)

**Comment by cebe** [comment]
there is already some JS code to deal with this. may need improvement though:

https://github.com/yiisoft/yii2-apidoc/blob/master/templates/bootstrap/layouts/main.php#L12-L21

**Comment by SilverFire** [comment]
Chrome. I'll fix

![](http://savepic.ru/8182061.png)
