### ISSUE TITLE
New highlighter problem: Broken styling in mixed blocks

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2-apidoc#34]
When the <code>```php</code> code block contains HTML, the Hightlight.php library renders it badly:

http://www.yiiframework.com/doc-2.0/guide-input-forms.html
![screenshot 2015-12-23 001](https://cloud.githubusercontent.com/assets/4499203/11985318/2066b16a-a9cc-11e5-80c9-3bf0e304dfc3.png)

http://www.yiiframework.com/doc-2.0/guide-start-forms.html#creating-views
![screenshot 2015-12-23 002](https://cloud.githubusercontent.com/assets/4499203/11985319/2067ceec-a9cc-11e5-8efe-ace5e857be38.png)

**Comment by arogachev** [comment]
Related - https://github.com/scrivo/highlight.php/issues/74.
