### ISSUE TITLE
api.css not included

### ISSUE THREAD

**Issue by matjack1** [yiisoft/yii2-apidoc#4]
Hi @cebe,
following your commit https://github.com/yiisoft/yii2-apidoc/commit/13ba0537b53ccda5299f99d5b22c4724a4a5c6b9 I was checking how it was rendered now, but it looks like the file ```api.css``` is not included in the building process (https://github.com/yiisoft/yii2-apidoc/blob/master/templates/bootstrap/assets/AssetBundle.php#L22).

Is that deliberate? If so, would be better to move the CSS rule in ```style.css```?

If I understand the rationale I'm more than happy to help out a bit with some code :)

**Comment by cebe** [comment]
sounds like a bug, either both css files should be included or they should be merged. Merging sounds more reasonable to me. You can work on that if you want.
