### ISSUE TITLE
No indication for deprecated methods

### ISSUE THREAD

**Issue by emados** [yiisoft/yii2-apidoc#5]
Deprecated methods are displayed like others, without any indication that it has been deprecated. It does not even include that in the description of the method, and the `@deprecated` annotation is just removed.

**Comment by cebe** [comment]
It is working for classes: http://www.yiiframework.com/doc-2.0/yii-authclient-clients-googleopenid.html
For methods this has not been added in the template but is available in the model layer already.

**Comment by EmadOmar** [comment]
Got it, thanks for explanation.

**Comment by cebe** [comment]
Fixed, thanks for reporting!
