### ISSUE TITLE
Code Highlighter

### ISSUE THREAD

**Issue by Julian-B90** [yiisoft/yii2-apidoc#54]
At the moment only the php code highlighter is working.
 
When i want to use the js code highlighter i use this ```js
but the code is not highlightet.

**Comment by cebe** [comment]
which version are you using? this should work on master already.

**Comment by Julian-B90** [comment]
i am using this version 2.0.4

**Comment by Julian-B90** [comment]
okay i test the dev-master. I will write my experience in few minutes

**Comment by Julian-B90** [comment]
i looks good. Thank you very mutch @cebe.
