### ISSUE TITLE
Description of the method of how to wrap

### ISSUE THREAD

**Issue by phpyii** [yiisoft/yii2-apidoc#56]
Description of the method of how to wrap?
How to use the markdown title  #?  
Not to do it
```php
    /**
     *### 通用登录
     *#### 参数:
     */
```

**Comment by cebe** [comment]
the first line is a short description which does not allow markdown formating.
after that, a blank line should follow.
In all lines below markdown should work.

```php
/**
 * short description here
 *
 * ## this is a headline
 *
 * Paragraph here
 * 
 */
