### ISSUE TITLE
"view source on github" button

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2-apidoc#59]
Hi,

is there a possibility to enable the "view source on github" button and provided the github source link? Or how can enable this feature?

thanks for taking time.

**Comment by cebe** [comment]
this feature is currenly only implemented for yii framework and official extensions: https://github.com/yiisoft/yii2-apidoc/blob/bab23f2bd7393345dd7b285f41bbbc518e9ecf76/templates/bootstrap/ApiRenderer.php#L98-L127

**Comment by nadar** [comment]
We just forked the repo and added an inline configuration:

https://github.com/luyadev/yii2-apidoc/blob/master/templates/bootstrap/ApiRenderer.php#L96-L130

Maybe this helps someone to extend the yii2-apidoc for its own.

(@cebe an option to provide a config which could contain this [and other] settings would be a very elegang solutions `./vendor/bin/apidoc --config=path/to/config.php`, then it would be easy to pass this option to the class)
