### ISSUE TITLE
\yii\rest\Controller::enableCsrfValidation documentation appears twice

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2-apidoc#61]
The documentation is inherited from \yii\web\Controller, [where it's fine](http://www.yiiframework.com/doc-2.0/yii-web-controller.html#$enableCsrfValidation-detail), but here it appears twice:

http://www.yiiframework.com/doc-2.0/yii-rest-controller.html#%24enableCsrfValidation-detail

**Comment by cebe** [comment]
fixed, thanks for reporting!
