### ISSUE TITLE
yii\apidoc\templates\bootstrap\SideNavWidget ... possibly doesn't belong here?

### ISSUE THREAD

**Issue by p2made** [yiisoft/yii2-apidoc#64]
Recently I stumbled across [SideNavWidget](http://www.yiiframework.com/doc-2.0/yii-apidoc-templates-bootstrap-sidenavwidget.html) in the Yii 2 docs. It looked like a solution I was looking for, & I was glad :)

However the file looks like a complete misfit for the location...
- The code looks like a Nav widget
- The documentation looks like for a Nav widget

But the location, `yii\apidoc\templates`, seems wrong for it. Could this be a file misplaced?

**Comment by cebe** [comment]
well it was just placed here as it was made solely for the docs nav without the intend to make it availble in the bootstrap extension. we could make it part of bootstrap though, if that makes sense.

**Comment by p2made** [comment]
That would be really neat as it is a very useful widget.

**Comment by cebe** [comment]
closing as there does not seem to be much interest in this issue. If someone wants to send a pull request, please do.
