### ISSUE TITLE
yiirequirementchecker.html generation problem

### ISSUE THREAD

**Issue by vmsubbotin** [yiisoft/yii2-apidoc#65]
Simple see http://www.yiiframework.com/doc-2.0/yiirequirementchecker.html and http://www.yiiframework.com/doc-2.0/index.html -> Not namespaced classes

**Comment by cebe** [comment]
what is the problem?

**Comment by cebe** [comment]
okay, now I see it.

**Comment by cebe** [comment]
fixed, thanks for reporting!
