### ISSUE TITLE
Error: Uninitialized string offset: 0

### ISSUE THREAD

**Issue by itnelo** [yiisoft/yii2-apidoc#68]
### What steps will reproduce the problem?

vendor/bin/apidoc api . docs/api

```
Searching files to process... done.
Loading apidoc data from cache... done.
Checking for updated files... done.
0 files to update.
Processing files... done.
Updating cross references and backlinks... done.
Rendering files: 84% (269/318) ETA: 10 sec.   Error: Uninitialized string offset: 0
```

How can i find files that broke this process?

### What's expected?

Successful docs creation.

### What do you get instead?

Error: Uninitialized string offset: 0 (after "84% files rendered" status)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.8
| PHP version      | 5.4.45-1~dotdeb+6.1
| Operating system | Debian 6.0.4 (Squeeze)

**Comment by cebe** [comment]
can you enable YII_DEBUG in the apidoc command: https://github.com/yiisoft/yii2-apidoc/blob/master/apidoc#L11 ? and paste the stack trace?

**Comment by itnelo** [comment]
Rendering files: 45% (146/318) ETA: 29 sec.   PHP Notice 'yii\base\ErrorException' with message 'Uninitialized string offset: 0'

in /path/to/vendor/yiisoft/yii2-apidoc/renderers/BaseRenderer.php:92

Stack trace:
#0 /path/to/vendor/yiisoft/yii2-apidoc/templates/html/views/methodDetails.php(58): yii\apidoc\templates\html\ApiRenderer->renderMethodSignature()
#1 /path/to/vendor/yiisoft/yii2/base/View.php(325): ::unknown()
#2 /path/to/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile()
#3 /path/to/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile()
#4 /path/to/vendor/yiisoft/yii2-apidoc/templates/html/views/type.php(108): yii\base\View->render()
#5 /path/to/vendor/yiisoft/yii2/base/View.php(325): ::unknown()
#6 /path/to/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile()
#7 /path/to/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile()
#8 /path/to/vendor/yiisoft/yii2-apidoc/templates/html/ApiRenderer.php(135): yii\base\View->render()
#9 /path/to/vendor/yiisoft/yii2-apidoc/templates/html/ApiRenderer.php(106): yii\apidoc\templates\html\ApiRenderer->renderWithLayout()
#10 /path/to/vendor/yiisoft/yii2-apidoc/templates/bootstrap/ApiRenderer.php(46): yii\apidoc\templates\html\ApiRenderer->render()
#11 /path/to/vendor/yiisoft/yii2-apidoc/commands/ApiController.php(112): yii\apidoc\templates\bootstrap\ApiRenderer->render()
#12 /path/to/vendor/yiisoft/yii2/base/InlineAction.php(55): yii\apidoc\commands\ApiController->actionIndex()
#13 /path/to/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array:{/path/to/vendor/yiisoft/yii2/base/InlineAction.php:55}()
#14 /path/to/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams()
#15 /path/to/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction()
#16 /path/to/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction()
#17 /path/to/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction()
#18 /path/to/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction()
#19 /path/to/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#20 /path/to/vendor/yiisoft/yii2-apidoc/apidoc(53): yii\base\Application->run()
#21 {main}

**Comment by itnelo** [comment]
got it.

In one of my classes i have invalid annotation:

`@var Route[]|[]`

It completely broke apidoc.

`$types` become

```
0 => [
    0 => '\\app\\modules\\routing\\models\\Route[]'
    1 => '[]'
]
```

and in case of '[]' error was thrown

**Comment by cebe** [comment]
fixed, thanks for digging into it!

**Comment by santosh-1265** [comment]
cant figure out whats wrong here
Rendering files: 89% (3112/3472) ETA: 16 sec.   PHP Notice 'yii\base\ErrorException' with message 'Uninitialized string offset: 0'

in /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/models/TypeDoc.php:57

Stack trace:
#0 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/models/TypeDoc.php(57): yii\base\ErrorHandler->handleError(8, 'Uninitialized s...', '/home/cloudadic...', 57, Array)
#1 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/models/ClassDoc.php(45): yii\apidoc\models\TypeDoc->findSubject('')
#2 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdownTrait.php(55): yii\apidoc\models\ClassDoc->findSubject('')
#3 /home/cloudadic/service/vendor/cebe/markdown/Parser.php(345): yii\apidoc\helpers\ApiMarkdown->parseApiLinks('[[HTMLPurifier_...')
#4 /home/cloudadic/service/vendor/cebe/markdown/Parser.php(85): cebe\markdown\Parser->parseInline('[[HTMLPurifier_...')
#5 /home/cloudadic/service/vendor/yiisoft/yii2/helpers/BaseMarkdown.php(84): cebe\markdown\Parser->parseParagraph('[[HTMLPurifier_...')
#6 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/helpers/ApiMarkdown.php(232): yii\helpers\BaseMarkdown::processParagraph('[[HTMLPurifier_...', 'api')
#7 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/views/seeAlso.php(16): yii\apidoc\helpers\ApiMarkdown::process('[[HTMLPurifier_...', Object(yii\apidoc\models\ClassDoc), true)
#8 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(330): require('/home/cloudadic...')
#9 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/cloudadic...', Array)
#10 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/cloudadic...', Array, NULL)
#11 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/views/methodDetails.php(63): yii\base\View->render('seeAlso', Array)
#12 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(330): require('/home/cloudadic...')
#13 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/cloudadic...', Array)
#14 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/cloudadic...', Array, NULL)
#15 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/views/type.php(108): yii\base\View->render('@yii/apidoc/tem...', Array)
#16 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(330): require('/home/cloudadic...')
#17 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/cloudadic...', Array)
#18 /home/cloudadic/service/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/cloudadic...', Array, Object(yii\apidoc\templates\bootstrap\ApiRenderer))
#19 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/ApiRenderer.php(135): yii\base\View->render('@yii/apidoc/tem...', Array, Object(yii\apidoc\templates\bootstrap\ApiRenderer))
#20 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/html/ApiRenderer.php(105): yii\apidoc\templates\html\ApiRenderer->renderWithLayout('@yii/apidoc/tem...', Array)
#21 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/templates/bootstrap/ApiRenderer.php(46): yii\apidoc\templates\html\ApiRenderer->render(Object(yii\apidoc\models\Context), './output')
#22 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/commands/ApiController.php(112): yii\apidoc\templates\bootstrap\ApiRenderer->render(Object(yii\apidoc\models\Context), './output')
#23 [internal function]: yii\apidoc\commands\ApiController->actionIndex(Array, './output')
#24 /home/cloudadic/service/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /home/cloudadic/service/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#26 /home/cloudadic/service/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#27 /home/cloudadic/service/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#28 /home/cloudadic/service/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('api', Array)
#29 /home/cloudadic/service/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('api', Array)
#30 /home/cloudadic/service/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#31 /home/cloudadic/service/vendor/yiisoft/yii2-apidoc/apidoc(52): yii\base\Application->run()
#32 {main}

**Comment by cebe** [comment]
please open a new issue.

**Comment by santosh-1265** [comment]
you can find the stack trace above
