### ISSUE TITLE
magic @property before class declaration

### ISSUE THREAD

**Issue by aleksanderd** [yiisoft/yii2-apidoc#7]
Hi!

I just noticed a @property which described before a class declarations do not rendered to result apidoc htmls :(

For example, even AR-model classes genereated by _gii_ have such @property comments for each db field, but they do not appers in the docs.

Other case is for AR-relations. If a model have a relation to (for ex) User model, there is a method like:

``` php
/**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
```

While the method `$model->getUser()` returns ActiveQuery, the magic property `$model->user` will return User class instance ([see why](https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L247)). I think, it is enough reason to describe the method and property separately.

It is possible to put magic @property comments/descriptions to the result docs indepenently from the getter/setter method?

Thank you!

**Comment by brandonkelly** [comment]
Ditto for `@method`! And probably goes without saying, but any `[[Class::property]]` / `[[Class::method()]]` cross links should also be able to resolve to doc block-defined `@property` / `@method`s too.

**Comment by brandonkelly** [comment]
Maybe also worth mentioning that there are cases where Yii’s own doc blocks are expecting this feature to exist. For example the `[[scenario]]` link in [yii\base\Model::validate()](http://www.yiiframework.com/doc-2.0/yii-base-model.html#validate()-detail).
