### ISSUE TITLE
yii2-apidoc could not be installed with Yii version 2.0.8

### ISSUE THREAD

**Issue by hugebug4ever** [yiisoft/yii2-apidoc#70]
### What steps will reproduce the problem?
as I run "composer require --prefer-dist yiisoft/yii2-apidoc"
the command failed with the infomation: it only support 2.0.1 ~ 2.0.5

### What's expected?
install success

### What do you get instead?
install failed  it only support 2.0.1 ~ 2.0.5

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.8
| PHP version      | 5.4
| Operating system | centos 6.5

**Comment by cebe** [comment]
please include the full output of composer

**Comment by hugebug4ever** [comment]
Here I attached the composer and the output. Thank you for help

[output.txt](https://github.com/yiisoft/yii2-apidoc/files/314153/output.txt)
[composer.txt](https://github.com/yiisoft/yii2-apidoc/files/314155/composer.txt)

**Comment by cebe** [comment]
@hugebug4ever composer require will only install the package if composer does not have to touch any other package for intsalling it. in this case it has to switch the version of the `cebe/markdown` library, so you have to manually add `yiisoft/yii2-apidoc` to your composer.json and then run `composer update`.
