### ISSUE TITLE
Can't be install by composer automatically.

### ISSUE THREAD

**Issue by hezll** [yiisoft/yii2-apidoc#72]
### What steps will reproduce the problem?
I try to use the command 
php composer.phar require --prefer-dist yiisoft/yii2-apidoc

it can not be installed because the apidoc need "cebe/markdown": "1.0.2",
but it automatically add the newest version of markdown 1.1.0
so the files are conflict.
### What's expected?
no errors
### What do you get instead?
I try to install each component one by one 

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.8
| PHP version      | php7
| Operating system | windows

**Comment by cebe** [comment]
adding it to the composer.json file manually and running update will solve this. ` require ` not working here is a feature of composer to protect you from breaking existing dependencies.

**Comment by cebe** [comment]
I have updated the README to be more clear about this.
