### ISSUE TITLE
Undefined index in createTypeLink of BaseRenderer

### ISSUE THREAD

**Issue by Luciuz** [yiisoft/yii2-apidoc#77]
`92:                           } elseif ($type[0] !== '\\' &&`

Index 0 is undefined. How it can be?

**Comment by samdark** [comment]
Please provide a way to reproduce the problem.

**Comment by Luciuz** [comment]
Problem is solved: `@return []` is replaced by `@return array` in my code

**Comment by cebe** [comment]
still should not crash.

**Comment by samdark** [comment]
@cebe any idea on how to reproduce it?

**Comment by cebe** [comment]
thought it was by adding `@return []` to a docblock but I am not able to reproduce it that way.

**Comment by cebe** [comment]
I see, this has been fixed already https://github.com/yiisoft/yii2-apidoc/commit/ba1c6be007f16f01803aac7bf8f8886e90471289
