### ISSUE TITLE
API link is missing when ends with colon

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2-apidoc#78]
### What steps will reproduce the problem?

Open page https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#saving-data-life-cycle-

See the numbered list. Each point begins from a link for event handling method.

Open http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#saving-data-life-cycle
### What's expected?

Links are present
### What do you get instead?

Links are missing
### Additional info

Guess it happens because of `:` (colon) after the link.

Originally reported in https://github.com/yiisoft/yii2/pull/12346

**Comment by cebe** [comment]
weird thing, thanks for reporting. Will check it. seems to be a bug in the markdown parser though.

**Comment by CedricYii** [comment]
Doesn't seem to be related to the `:` right after the link since it doesn't work for the first sentence either:
````When calling [[yii\db\ActiveRecord::save()|save()]] to insert or ...````

**Comment by arogachev** [comment]
It's rendered as expected now.
