### ISSUE TITLE
is bug?

### ISSUE THREAD

**Issue by dingzhihao** [yiisoft/yii2-apidoc#79]
### What steps will reproduce the problem?

the file [BaseDoc.php](https://github.com/yiisoft/yii2-apidoc/blob/master/models/BaseDoc.php) on line 159 has a problem with chinese. And the error is `Processing files... 0% (0/1) ETA: n/a   Error: mb_strpos(): Offset not contained in string`.

here is the test code
```php
$text = "总页数";
var_dump(extractFirstSentence($text));

function extractFirstSentence($text)
{
    if (mb_strlen($text) > 4 && ($pos = mb_strpos($text, '.', 4, 'utf-8')) !== false) {                                         
        $sentence = mb_substr($text, 0, $pos + 1, 'utf-8');
        if (mb_strlen($text) >= $pos + 3) {
            $abbrev = mb_substr($text, $pos - 1, 4); 
            if ($abbrev === 'e.g.' || $abbrev === 'i.e.') { // do not break sentence after abbreviation
                $sentence .= static::extractFirstSentence(mb_substr($text, $pos + 1));
            }   
        }   
        return $sentence;
    } else {
        return $text;
    }   
}
```

### What's expected?

no errors

### What do you get instead?

change to this will be fine

```php
if (mb_strlen($text, 'utf-8') > 4 && ($pos = mb_strpos($text, '.', 4, 'utf-8')) !== false) {
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by cebe** [comment]
Fixed, thanks for reporting!
