### ISSUE TITLE
Updating nikic/php-parser to 1.0

### ISSUE THREAD

**Issue by wilwade** [yiisoft/yii2-apidoc#8]
Any interest/work in updating nikic/php-parser to 1.0+? I'll work on doing it if no one is and it is desired.

Here is the info on the upgrade: https://github.com/nikic/PHP-Parser/blob/1.x/UPGRADE-1.0.md

**Comment by cebe** [comment]
there is a dependency that depends on the old version: https://github.com/phpDocumentor/Reflection/issues/34 Otherwise I am all for it.

**Comment by wilwade** [comment]
@cebe I'll go upstream and see what I can do there first then. I'll close this for now and reopen when phpDocumentor/Reflection supports it and see then about upgrading both.

**Comment by samdark** [comment]
:+1:

**Comment by wilwade** [comment]
Update: The develop branch of Reflection is already updated to PHP-Parser 1.0 (https://github.com/phpDocumentor/Reflection/blob/develop/composer.json), so it is just a matter of waiting for phpDocumentor/Reflection 2.0 to go stable (and then update here for that). I'll try to keep an eye on it.

**Comment by cebe** [comment]
thanks for checking that!

**Comment by Luciuz** [comment]
Howdy?

**Comment by cebe** [comment]
Dependency has been updated and a version 2.1 is released.
